"""changed playlistSong to a joins table

Revision ID: 021792c2f794
Revises: 87d8ef30f35d
Create Date: 2021-06-10 18:36:55.316953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '021792c2f794'
down_revision = '87d8ef30f35d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlistSongs', sa.Column('playlist_id', sa.Integer(), nullable=False))
    op.add_column('playlistSongs', sa.Column('song_id', sa.Integer(), nullable=False))
    op.drop_constraint('playlistSongs_playlistId_fkey', 'playlistSongs', type_='foreignkey')
    op.drop_constraint('playlistSongs_songId_fkey', 'playlistSongs', type_='foreignkey')
    op.create_foreign_key(None, 'playlistSongs', 'songs', ['song_id'], ['id'])
    op.create_foreign_key(None, 'playlistSongs', 'playlists', ['playlist_id'], ['id'])
    op.drop_column('playlistSongs', 'id')
    op.drop_column('playlistSongs', 'order')
    op.drop_column('playlistSongs', 'playlistId')
    op.drop_column('playlistSongs', 'songId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlistSongs', sa.Column('songId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('playlistSongs', sa.Column('playlistId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('playlistSongs', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('playlistSongs', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"playlistSongs_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'playlistSongs', type_='foreignkey')
    op.drop_constraint(None, 'playlistSongs', type_='foreignkey')
    op.create_foreign_key('playlistSongs_songId_fkey', 'playlistSongs', 'songs', ['songId'], ['id'])
    op.create_foreign_key('playlistSongs_playlistId_fkey', 'playlistSongs', 'playlists', ['playlistId'], ['id'])
    op.drop_column('playlistSongs', 'song_id')
    op.drop_column('playlistSongs', 'playlist_id')
    # ### end Alembic commands ###
