"""create all tables

Revision ID: 09ae2054339c
Revises: 418e09ec2bef
Create Date: 2021-05-06 12:09:39.677515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09ae2054339c'
down_revision = '418e09ec2bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('imageUrl', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('imageUrl', sa.String(), nullable=True))
    op.add_column('playlists', sa.Column('imageUrl', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlists', 'imageUrl')
    op.drop_column('artists', 'imageUrl')
    op.drop_column('albums', 'imageUrl')
    # ### end Alembic commands ###
