"""fixed song length

Revision ID: 5f13779a965c
Revises: fd4506c85821
Create Date: 2021-05-07 19:32:00.187212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f13779a965c'
down_revision = 'fd4506c85821'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'length',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'length',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
