"""final adjustments

Revision ID: 87d8ef30f35d
Revises: f2f86bbdfb49
Create Date: 2021-05-13 12:39:04.818417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87d8ef30f35d'
down_revision = 'f2f86bbdfb49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'releaseDate')
    op.drop_column('albums', 'order')
    op.drop_column('songs', 'releaseDate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('releaseDate', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('albums', sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('albums', sa.Column('releaseDate', sa.DATE(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
