"""fix nullable

Revision ID: f2f86bbdfb49
Revises: 2e9cd75d3c8c
Create Date: 2021-05-11 16:16:02.404213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f86bbdfb49'
down_revision = '2e9cd75d3c8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'artistId',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('songs', 'releaseDate',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('songs', 'releaseDate',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('songs', 'artistId',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
