"""fix  artists table

Revision ID: fd4506c85821
Revises: 09ae2054339c
Create Date: 2021-05-06 19:16:19.566136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd4506c85821'
down_revision = '09ae2054339c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('userId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'artists', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'artists', type_='foreignkey')
    op.drop_column('artists', 'userId')
    # ### end Alembic commands ###
